version: '3.4'

services:
  proxy:
    image: traefik:2.2
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: 
      context: ./backend
      target: django-dev
    labels:
      traefik.http.routers.web.rule: Host("2886795273-80-simba10.environments.katacoda.com") && PathPrefix("/admin")
      traefik.http.services.web.loadbalancer.server.port: 5000
  flask_web:
    build:
      context: ./backend
      target: flask-dev
    ports:
      - 7000:5000
    labels:
      traefik.http.routers.flask_web.rule: Host("2886795273-80-simba10.environments.katacoda.com/") && PathPrefix("/todos")
      traefik.http.services.flask_web.loadbalancer.server.port: 5000
