version: '3.4'

services:
  proxy:
    image: traefik:2.2
    command: --providers.docker
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: 
      context: ./backend
      target: django-dev
    labels:
      traefik.http.routers.web.rule: Host("docker") && PathPrefix("/admin")
      traefik.http.services.web.loadbalancer.server.port: 5000

  flask_web:
    build:
      context: ./backend
      target: flask-dev
    stdin_open: true
    labels:
      traefik.http.routers.flask_web.rule: Host("docker")
      traefik.http.services.flask_web.loadbalancer.server.port: 5000
