version: '3.2'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx:/etc/ngix/conf.d
    depends_on:
      - django_backend
      - flask_backend
    networks:
      - nginx_network
  django_backend:
    build: 
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
    entrypoint: 
      - /bin/sh
      - /app/docker/backend/wsgi-entrypoint.sh
    volumes:
      - static_volume:/app/backend/django_rest/static
    expose:
      - 8000
    networks:
      - nginx_network
  flask_backend:
    build:
      context: .
      dockerfile: ./docker/backend/flask/Dockerfile
    entrypoint: 
      - /bin/sh
      - /app/docker/backend/flask/wsgi-entrypoint.sh
    volumes:
      - static_volume:/app/backend/flask_rest/static
    expose:
      - 5000
    networks:
      - nginx_network
volumes:
  static_volume: {}

networks:
  nginx_network:
    driver: bridge
