version: '3.4'

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/etc/ngix/conf.d
    depends_on:
      - django_backend
      - flask_backend
  django_backend:
    build: 
      context: ./backend
      target: django-dev
    labels:
      traefik.http.routers.web.rule: Host("2886795273-80-simba10.environments.katacoda.com") && PathPrefix("/admin")
      traefik.http.services.web.loadbalancer.server.port: 5000
  flask_web:
    build:
      context: ./backend
      target: flask-dev
    ports:
      - 7000:5000
    labels:
      traefik.http.routers.flask_web.rule: Host("2886795273-80-simba10.environments.katacoda.com/") && PathPrefix("/todos")
      traefik.http.services.flask_web.loadbalancer.server.port: 5000
